name: Automated Trading

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trading:
    runs-on: ubuntu-latest
    env:
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}  # Define your Oanda API key as a secret
      OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}  # Define your Oanda account ID as a secret
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version from requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python your_script.py  # Replace with the name of your Python script

      # Optionally, you can add more steps for testing, linting, or deploying

